### ISSUE TITLE
Add Workflow - Contract and Owner Fields - values not returned

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#103]
The system displays this inconsistent error when user executes the add workflow - does not return values  for contract ad owner fields. This function sometimes work as expected. I was unable to isolate the cause of the error
![image](https://user-images.githubusercontent.com/8458252/36694299-f562821a-1b0b-11e8-8dab-8769a153701a.png)

**Comment by TaraF** [comment]
@ladejobi  I am unable to replicate.  Owner and Contract lists have both shown up every time for me.  Contract list has many blanks at the beginning, probably due to someone clicking "Add New Contract" without typing anything in. 

There are no service errors broken related to either of these lists being generated either.  

I don't think this is a viable bug unless you are able to give us step by step on how to replicate.

**Comment by ladejobi** [comment]
@TaraF seems i was able to isolate the issue. This bug is happening right after user deletes a SWMFAC record. To replicate delete a SWMFAC( doesn't matter if it's new or existing) then execute the Add SWMFAC or and Import workflow. The system will return blank fields for the Contract and owner fields.

**Comment by TaraF** [comment]
This is fixed in KCI dev.  Please test.

**Comment by ladejobi** [comment]
@TaraF great job! Bug fixed.
