### ISSUE TITLE
 New Relationship Class/Association -Not enforced on UI

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#24]
@Tara the way we show the BMP inspection to rating association and SWMFAC to rating association in the UI does not meet Kerry's requirement for the new relationship class below right? It's listed as 1:M for both relationships, but UI shows 1:1

![image](https://user-images.githubusercontent.com/8458252/32292692-43edd3ae-bf17-11e7-9bae-643d3d205ec2.png)

**Comment by TaraF** [comment]
Hi Feyi -- I think we discussed this one....the relationship is always 1:1 from inspection to rating.  I am not sure why she has it set 1:Many, unless its something she needs on the back end.  It shouldn't effect anything for the UI.  Requirements state 1:1, so I recommend we enforce that on the UI unless otherwise directed by stakeholders.

**Comment by ladejobi** [comment]
I agree @TaraF
