### ISSUE TITLE
Discard pop up error issue

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#96]
The system returns an inpplicable discard confirmation pop up message when: 
1. Executes a search and selects records from the location manager -
2. Executes an edit and clicks on another tab i.e reports

**Comment by ladejobi** [comment]
@TaraF I'm not encountering this issue in KCI and SHA DEV. The 1 issue doesn't occur consistently, it seems to occur after No. 2 issue is encountered.

**Comment by TaraF** [comment]
@ladejobi  -- this would be a purely flex issue, but the only way I can replicate it is to save an edit and then click on a tab before the edit has a chance to go through.  Flex is responding appropriately at that point, because it hasn't be saved yet.  

Long and short, this is not something we can control -- it has to do with a user switching before edit has gone through in the service (may be a slight lag time in SHA prod services).  

I don't think this is a bug to fix.

**Comment by ladejobi** [comment]
@TaraF i agree, this is not a bug. I waited to get the confirmation pop up and didn't encounter the issue when I switched tabs. It's weird I didn't encounter this amount of system lag prior to us deploying to prod.

**Comment by ladejobi** [comment]
@TaraF I agree. this is related to Prod services. Not encountering any lag in SHA Dev
