### ISSUE TITLE
Add workflow - System Lag Issue 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#97]
There's a significant time lag between when user completes the  Add SWMFAC workflow and when record is loaded in the results tab in production. This lag does not occur in SHA DEV.

**Comment by TaraF** [comment]
@ladejobi -- this is the service call to add a swmfac.  I don't think we can control how quickly the service goes through - especially since it is already quick in dev (meaning our processes in oracle are not holding it up).  There are several lagging production services I have noticed.  It likely has something to do with the production server -- nothing we can control at this point.

**Comment by ladejobi** [comment]
@TaraF I agree. this is related to Prod services. Not encountering any lag in SHA Dev
