### ISSUE TITLE
ADD Workflow - Geometry errors

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#99]
When user searches a newly created SWMFAC record, the system returns a geometry error and an infinite SWMFAC loading pop up window. To replicate:
1. Create a SWMFAC record and capture the SWMFAC No.
2. Search the record using the select by Form (The system newly created record is not shown on the map)
3. Select the record in the location manager 
4. System will return pop up errors.
![image](https://user-images.githubusercontent.com/8458252/36692959-ad5344d6-1b07-11e8-893f-9df9e30c11ce.png)

**Comment by TaraF** [comment]
@ladejobi is this happening in production too?

**Comment by TaraF** [comment]
Feyi confirmed -- not happening in PROD

**Comment by TaraF** [comment]
look into AddSWMFAC service in KCI dev, potentially fix, send to Mohsin and updates, push to SHA dev

**Comment by ladejobi** [comment]
This issue is happening in KCI dev.

**Comment by TaraF** [comment]
@ladejobi  -- this is fixed in KCI Dev -- the geometry error is gone, and results are being returned.  Also, you can do a map selection to get any new swmfac features added.

@mohsinkar  -- I am assigning to you also, because I noticed that after getting the info, the "gathering information. please wait...." spinner continues and freezes the screen.   this is probably related to another issue you are working on, but just wanted to make sure we catch it.   See screen capture:


![capture_swmfacgatheringspinner](https://user-images.githubusercontent.com/4104464/37052347-ef61e476-2170-11e8-9672-98b17c477be9.PNG)

**Comment by ladejobi** [comment]
@TaraF I was able to validate the fix for the geometry error. @mohsinkar i was able to replicate the gathering info error. we can close bug out once that issue is fixed

**Comment by mohsinkar** [comment]
related to the ADDSWMFAC issue.

**Comment by ladejobi** [comment]
no longer encountering issue, appears to be fixed
